//! Farneback optical flow parity tests against `OpenCV` reference.
//!
//! Golden `.flo` files under `tests/fixtures/` are generated by `OpenCV`'s
//! `calcOpticalFlowFarneback` with canonical parameters. Tests verify
//! mean EPE ≤ 0.1, max EPE ≤ 0.5.

use std::path::{Path, PathBuf};

use motionframe_engine::flow::farneback::farneback;
use motionframe_engine::io::tga::{load_rgba, premultiply_alpha};
use motionframe_engine::pipeline::{FarnebackParams, Flow, ImageF32};

/// Read a .flo or .flo.gz file (Middlebury format) into a Flow struct.
fn read_flo(path: &Path) -> Flow {
    use flate2::read::GzDecoder;
    use std::io::Read;

    let file =
        std::fs::File::open(path).unwrap_or_else(|e| panic!("Cannot open {}: {e}", path.display()));
    let mut buf = Vec::new();
    if path.extension().is_some_and(|e| e == "gz") {
        GzDecoder::new(file)
            .read_to_end(&mut buf)
            .unwrap_or_else(|e| panic!("Cannot decompress {}: {e}", path.display()));
    } else {
        std::io::BufReader::new(file)
            .read_to_end(&mut buf)
            .unwrap_or_else(|e| panic!("Cannot read {}: {e}", path.display()));
    }

    assert!(buf.len() >= 12, "File too small for .flo header");
    assert_eq!(&buf[0..4], b"PIEH", "Invalid .flo magic");

    let w = i32::from_le_bytes([buf[4], buf[5], buf[6], buf[7]]) as u32;
    let h = i32::from_le_bytes([buf[8], buf[9], buf[10], buf[11]]) as u32;

    let expected_size = 12 + (w as usize) * (h as usize) * 2 * 4;
    assert_eq!(buf.len(), expected_size, "File size mismatch");

    let mut data = vec![[0.0f32; 2]; (w as usize) * (h as usize)];
    let mut offset = 12;
    for pixel in &mut data {
        pixel[0] = f32::from_le_bytes([
            buf[offset],
            buf[offset + 1],
            buf[offset + 2],
            buf[offset + 3],
        ]);
        offset += 4;
        pixel[1] = f32::from_le_bytes([
            buf[offset],
            buf[offset + 1],
            buf[offset + 2],
            buf[offset + 3],
        ]);
        offset += 4;
    }

    Flow {
        width: w,
        height: h,
        data,
    }
}

/// Load a TGA frame, premultiply alpha, and convert to grayscale f32 (BT.601).
fn load_and_prepare(frame_num: u32) -> ImageF32 {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("fixtures")
        .join("explosion00")
        .join(format!("explosion00-frame{frame_num:03}.tga"));
    let rgba = load_rgba(&path).unwrap_or_else(|e| panic!("Cannot load {}: {e}", path.display()));
    let premul = premultiply_alpha(&rgba);
    rgba_to_gray_f32(&premul)
}

/// Convert premultiplied RGBA8 image to single-channel f32 grayscale using BT.601 weights.
/// Uses `OpenCV`-compatible fixed-point formula to produce integer-valued floats,
/// matching `cv2.cvtColor(img, COLOR_RGB2GRAY)` which outputs uint8.
fn rgba_to_gray_f32(img: &motionframe_engine::pipeline::ImageRgba8) -> ImageF32 {
    let mut result = ImageF32::zeros(img.width, img.height);
    for (i, chunk) in img.data.chunks_exact(4).enumerate() {
        let r = u32::from(chunk[0]);
        let g = u32::from(chunk[1]);
        let b = u32::from(chunk[2]);
        // OpenCV's fixed-point RGB2GRAY for uint8: (R*4899 + G*9617 + B*1868 + 8192) >> 14
        result.data[i] = ((r * 4899 + g * 9617 + b * 1868 + 8192) >> 14) as f32;
    }
    result
}

/// Compute End-Point Error (EPE) between two flow fields.
fn compute_epe(actual: &Flow, expected: &Flow) -> (f32, f32) {
    assert_eq!(actual.width, expected.width);
    assert_eq!(actual.height, expected.height);

    let mut sum_epe = 0.0f64;
    let mut max_epe = 0.0f32;
    let n = actual.data.len();

    for i in 0..n {
        let [ax, ay] = actual.data[i];
        let [ex, ey] = expected.data[i];
        let dx = ax - ex;
        let dy = ay - ey;
        let epe = dx.hypot(dy);
        sum_epe += f64::from(epe);
        if epe > max_epe {
            max_epe = epe;
        }
    }

    let mean_epe = (sum_epe / n as f64) as f32;
    (mean_epe, max_epe)
}

fn fixture_path(a: u32, b: u32) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("fixtures")
        .join(format!("explosion00_{a:03}_{b:03}.flo.gz"))
}

fn fixture_path_gauss(a: u32, b: u32) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("fixtures")
        .join(format!("explosion00_{a:03}_{b:03}_gauss.flo.gz"))
}

#[test]
fn farneback_parity_explosion00() {
    let pairs = [(1, 2), (10, 11), (25, 26), (40, 41), (60, 61)];
    let params = FarnebackParams {
        use_gaussian: false,
        ..FarnebackParams::default()
    };

    for (a, b) in pairs {
        let g1 = load_and_prepare(a);
        let g2 = load_and_prepare(b);
        let actual = farneback(&g1, &g2, &params);
        let expected = read_flo(&fixture_path(a, b));
        let (mean_epe, max_epe) = compute_epe(&actual, &expected);
        eprintln!("Pair ({a},{b}): mean EPE = {mean_epe:.6}, max EPE = {max_epe:.6}");
        assert!(
            mean_epe <= 0.1,
            "pair ({a},{b}): mean EPE {mean_epe:.4} > 0.1"
        );
        assert!(max_epe <= 0.5, "pair ({a},{b}): max EPE {max_epe:.4} > 0.5");
    }
}

#[test]
fn farneback_parity_explosion00_gaussian() {
    // Same OpenCV defaults, but with OPTFLOW_FARNEBACK_GAUSSIAN flag set.
    // Verifies the Gaussian-window code path matches OpenCV byte-for-similar.
    let pairs = [(1, 2), (10, 11), (25, 26), (40, 41), (60, 61)];
    let params = FarnebackParams {
        use_gaussian: true,
        ..FarnebackParams::default()
    };

    let mut failures = Vec::new();
    for (a, b) in pairs {
        let g1 = load_and_prepare(a);
        let g2 = load_and_prepare(b);
        let actual = farneback(&g1, &g2, &params);
        let expected = read_flo(&fixture_path_gauss(a, b));
        let (mean_epe, max_epe) = compute_epe(&actual, &expected);
        eprintln!("Gauss pair ({a},{b}): mean EPE = {mean_epe:.6}, max EPE = {max_epe:.6}");
        if mean_epe > 0.1 {
            failures.push(format!("pair ({a},{b}): mean EPE {mean_epe:.4} > 0.1"));
        }
        if max_epe > 0.5 {
            failures.push(format!("pair ({a},{b}): max EPE {max_epe:.4} > 0.5"));
        }
    }
    assert!(
        failures.is_empty(),
        "gaussian parity failures:\n{}",
        failures.join("\n")
    );
}

#[test]
#[allow(clippy::too_many_lines)]
fn diagnose_pair_10_11() {
    let g1 = load_and_prepare(10);
    let g2 = load_and_prepare(11);
    let params = FarnebackParams::default();
    let actual = farneback(&g1, &g2, &params);
    let expected = read_flo(&fixture_path_gauss(10, 11));

    let w = actual.width as usize;
    let h = actual.height as usize;
    let (mean_epe, fixture_max_epe) = compute_epe(&actual, &expected);
    assert!(
        mean_epe <= 0.1,
        "pair (10,11): mean EPE {mean_epe:.4} > 0.1"
    );
    assert!(
        fixture_max_epe <= 0.5,
        "pair (10,11): max EPE {fixture_max_epe:.4} > 0.5"
    );

    // Print flow statistics
    let mut max_ref_mag = 0.0f32;
    let mut sum_ref_mag = 0.0f64;
    for i in 0..actual.data.len() {
        let [ex, ey] = expected.data[i];
        let mag = ex.hypot(ey);
        sum_ref_mag += f64::from(mag);
        if mag > max_ref_mag {
            max_ref_mag = mag;
        }
    }
    eprintln!(
        "Reference flow: mean mag = {:.4}, max mag = {:.4}",
        sum_ref_mag / (w * h) as f64,
        max_ref_mag
    );

    // Find pixel with max EPE
    let mut max_epe = 0.0f32;
    let mut max_epe_pos = (0usize, 0usize);
    for y in 0..h {
        for x in 0..w {
            let i = y * w + x;
            let [ax, ay] = actual.data[i];
            let [ex, ey] = expected.data[i];
            let epe = (ax - ex).hypot(ay - ey);
            if epe > max_epe {
                max_epe = epe;
                max_epe_pos = (x, y);
            }
        }
    }
    let (mx, my) = max_epe_pos;
    let mi = my * w + mx;
    eprintln!(
        "Max EPE at ({mx},{my}): actual=[{:.4},{:.4}], ref=[{:.4},{:.4}], epe={max_epe:.4}",
        actual.data[mi][0], actual.data[mi][1], expected.data[mi][0], expected.data[mi][1]
    );

    // Print center pixel comparison
    let cx = w / 2;
    let cy = h / 2;
    let ci = cy * w + cx;
    eprintln!(
        "Center ({cx},{cy}): actual=[{:.6},{:.6}], ref=[{:.6},{:.6}], epe={:.6}",
        actual.data[ci][0],
        actual.data[ci][1],
        expected.data[ci][0],
        expected.data[ci][1],
        (actual.data[ci][0] - expected.data[ci][0])
            .hypot(actual.data[ci][1] - expected.data[ci][1])
    );

    // Compute EPE distribution: how many pixels > 0.1, > 0.5, > 1.0
    let mut count_01 = 0u32;
    let mut count_05 = 0u32;
    let mut count_10 = 0u32;
    for i in 0..actual.data.len() {
        let [ax, ay] = actual.data[i];
        let [ex, ey] = expected.data[i];
        let epe = (ax - ex).hypot(ay - ey);
        if epe > 0.1 {
            count_01 += 1;
        }
        if epe > 0.5 {
            count_05 += 1;
        }
        if epe > 1.0 {
            count_10 += 1;
        }
    }
    let total = (w * h) as f32;
    eprintln!(
        "EPE > 0.1: {} ({:.2}%)",
        count_01,
        count_01 as f32 / total * 100.0
    );
    eprintln!(
        "EPE > 0.5: {} ({:.2}%)",
        count_05,
        count_05 as f32 / total * 100.0
    );
    eprintln!(
        "EPE > 1.0: {} ({:.2}%)",
        count_10,
        count_10 as f32 / total * 100.0
    );
    assert_eq!(count_05, 0, "pair (10,11): pixels with EPE > 0.5");
    assert_eq!(count_10, 0, "pair (10,11): pixels with EPE > 1.0");

    // Check for scale bias: compute ratio actual/expected for well-defined pixels
    let mut scale_ratios_x = Vec::new();
    let mut scale_ratios_y = Vec::new();
    for i in 0..actual.data.len() {
        let [ex, ey] = expected.data[i];
        let [ax, ay] = actual.data[i];
        if ex.abs() > 0.5 {
            scale_ratios_x.push(ax / ex);
        }
        if ey.abs() > 0.5 {
            scale_ratios_y.push(ay / ey);
        }
    }
    if !scale_ratios_x.is_empty() {
        scale_ratios_x.sort_by(|a, b| a.partial_cmp(b).unwrap());
        let median_x = scale_ratios_x[scale_ratios_x.len() / 2];
        eprintln!(
            "Scale ratio (actual/expected) median X: {median_x:.4} (N={})",
            scale_ratios_x.len()
        );
        assert!(median_x.is_finite(), "median X scale ratio must be finite");
    }
    if !scale_ratios_y.is_empty() {
        scale_ratios_y.sort_by(|a, b| a.partial_cmp(b).unwrap());
        let median_y = scale_ratios_y[scale_ratios_y.len() / 2];
        eprintln!(
            "Scale ratio (actual/expected) median Y: {median_y:.4} (N={})",
            scale_ratios_y.len()
        );
        assert!(median_y.is_finite(), "median Y scale ratio must be finite");
    }
}

#[test]
fn diagnose_single_level() {
    let g1 = load_and_prepare(10);
    let g2 = load_and_prepare(11);

    // Test with 1 level, 1 iteration (simplest case)
    let params_1l1i = FarnebackParams {
        levels: 1,
        iterations: 1,
        ..FarnebackParams::default()
    };
    let flow_1l1i = farneback(&g1, &g2, &params_1l1i);
    let expected = read_flo(&fixture_path_gauss(10, 11));
    let (mean_epe_1l1i, max_epe_1l1i) = compute_epe(&flow_1l1i, &expected);

    let w = flow_1l1i.width as usize;
    let cx = w / 2;
    let cy = (flow_1l1i.height as usize) / 2;
    let ci = cy * w + cx;
    eprintln!(
        "1 level, 1 iter: center=[{:.6},{:.6}], ref=[{:.6},{:.6}], mean_epe={:.4}",
        flow_1l1i.data[ci][0],
        flow_1l1i.data[ci][1],
        expected.data[ci][0],
        expected.data[ci][1],
        mean_epe_1l1i
    );

    // 1 level, 5 iterations
    let params_1l5i = FarnebackParams {
        levels: 1,
        iterations: 5,
        ..FarnebackParams::default()
    };
    let flow_1l5i = farneback(&g1, &g2, &params_1l5i);
    let (mean_epe_1l5i, max_epe_1l5i) = compute_epe(&flow_1l5i, &expected);
    let ci2 = cy * w + cx;
    eprintln!(
        "1 level, 5 iter: center=[{:.6},{:.6}], mean_epe={:.4}",
        flow_1l5i.data[ci2][0], flow_1l5i.data[ci2][1], mean_epe_1l5i
    );

    // Full 8 levels, 1 iteration
    let params_8l1i = FarnebackParams {
        levels: 8,
        iterations: 1,
        ..FarnebackParams::default()
    };
    let flow_8l1i = farneback(&g1, &g2, &params_8l1i);
    let (mean_epe_8l1i, max_epe_8l1i) = compute_epe(&flow_8l1i, &expected);
    eprintln!(
        "8 levels, 1 iter: center=[{:.6},{:.6}], mean_epe={:.4}",
        flow_8l1i.data[ci][0], flow_8l1i.data[ci][1], mean_epe_8l1i
    );

    // Full 8 levels, 5 iterations (default)
    let params_full = FarnebackParams::default();
    let flow_full = farneback(&g1, &g2, &params_full);
    let (mean_epe_full, max_epe_full) = compute_epe(&flow_full, &expected);
    eprintln!(
        "8 levels, 5 iter: center=[{:.6},{:.6}], mean_epe={:.4}",
        flow_full.data[ci][0], flow_full.data[ci][1], mean_epe_full
    );
    assert!(mean_epe_1l1i.is_finite(), "1 level, 1 iter mean EPE");
    assert!(max_epe_1l1i.is_finite(), "1 level, 1 iter max EPE");
    assert!(mean_epe_1l5i.is_finite(), "1 level, 5 iter mean EPE");
    assert!(max_epe_1l5i.is_finite(), "1 level, 5 iter max EPE");
    assert!(mean_epe_8l1i.is_finite(), "8 levels, 1 iter mean EPE");
    assert!(max_epe_8l1i.is_finite(), "8 levels, 1 iter max EPE");
    assert!(
        mean_epe_full <= 0.1,
        "default pair (10,11): mean EPE {mean_epe_full:.4} > 0.1"
    );
    assert!(
        max_epe_full <= 0.5,
        "default pair (10,11): max EPE {max_epe_full:.4} > 0.5"
    );

    // Test with 2, 3, 4 levels to see where pyramid breaks
    for num_levels in 2..=8 {
        let params = FarnebackParams {
            levels: num_levels,
            iterations: 1,
            ..FarnebackParams::default()
        };
        let f = farneback(&g1, &g2, &params);
        let (epe, _) = compute_epe(&f, &expected);
        eprintln!(
            "{} levels, 1 iter: center=[{:.3},{:.3}], mean_epe={:.4}",
            num_levels, f.data[ci][0], f.data[ci][1], epe
        );
        assert!(
            epe.is_finite(),
            "{num_levels} levels, 1 iter mean EPE must be finite"
        );
    }

    // Print pyramid sizes
    eprintln!("Image size: {}x{}", g1.width, g1.height);
    eprintln!("Pyramid sizes (coarsest first):");
    let pyr = motionframe_engine::flow::pyramid::build_pyramid(&g1, 8, 0.5);
    assert_eq!(pyr.len(), 8, "pyramid should contain requested levels");
    for (i, p) in pyr.iter().enumerate() {
        eprintln!("  Level {}: {}x{}", i, p.width, p.height);
        assert!(p.width > 0, "pyramid level {i} width");
        assert!(p.height > 0, "pyramid level {i} height");
    }
}

#[test]
#[allow(clippy::many_single_char_names, clippy::suspicious_operation_groupings)]
fn diagnose_poly_coefficients() {
    let g1 = load_and_prepare(10);
    let g2 = load_and_prepare(11);
    let poly1 = motionframe_engine::flow::poly::poly_expansion(&g1, 5, 1.5);
    let poly2 = motionframe_engine::flow::poly::poly_expansion(&g2, 5, 1.5);
    let w = g1.width as usize;
    let cx = w / 2;
    let cy = (g1.height as usize) / 2;
    let ci = cy * w + cx;
    let [r4_1, r6_1, r5_1, r2_1, r3_1] = poly1.data[ci];
    let [r4_2, r6_2, r5_2, r2_2, r3_2] = poly2.data[ci];
    eprintln!("Poly1 at center ({cx},{cy}): r4={r4_1:.6}, r6={r6_1:.6}, r5={r5_1:.6}, r2={r2_1:.6}, r3={r3_1:.6}");
    eprintln!("Poly2 at center ({cx},{cy}): r4={r4_2:.6}, r6={r6_2:.6}, r5={r5_2:.6}, r2={r2_2:.6}, r3={r3_2:.6}");

    // Compute the flow equation terms at center (like update_flow does)
    let a = (r4_1 + r4_2) * 0.5;
    let b = (r6_1 + r6_2) * 0.25;
    let c = (r5_1 + r5_2) * 0.5;
    let d = (r2_2 - r2_1) * 0.5;
    let e = (r3_2 - r3_1) * 0.5;
    let g11 = a * a + b * b;
    let g12 = a * b + b * c;
    let g22 = b * b + c * c;
    let h1 = a * d + b * e;
    let h2 = b * d + c * e;
    eprintln!("Per-pixel at center: a={a:.6}, b={b:.6}, c={c:.6}, d={d:.6}, e={e:.6}");
    eprintln!("G=[{g11:.6}, {g12:.6}; {g12:.6}, {g22:.6}], h=[{h1:.6}, {h2:.6}]");
    let det = g11 * g22 - g12 * g12;
    let fx = (g22 * h1 - g12 * h2) / det;
    let fy = (g11 * h2 - g12 * h1) / det;
    eprintln!("Single-pixel flow (no window): [{fx:.6}, {fy:.6}]");
    for (name, value) in [
        ("a", a),
        ("b", b),
        ("c", c),
        ("d", d),
        ("e", e),
        ("g11", g11),
        ("g12", g12),
        ("g22", g22),
        ("h1", h1),
        ("h2", h2),
        ("det", det),
        ("fx", fx),
        ("fy", fy),
    ] {
        assert!(value.is_finite(), "{name} must be finite");
    }
    assert!(det.abs() > f32::EPSILON, "flow equation determinant");

    // Also print the gray values at center to verify image loading
    eprintln!("Gray1 center: {:.2}", g1.data[ci]);
    eprintln!("Gray2 center: {:.2}", g2.data[ci]);
    assert!(
        (0.0..=255.0).contains(&g1.data[ci]),
        "gray1 center must be uint8 range"
    );
    assert!(
        (0.0..=255.0).contains(&g2.data[ci]),
        "gray2 center must be uint8 range"
    );
}

#[test]
fn find_max_epe_pixel() {
    let g1 = load_and_prepare(10);
    let g2 = load_and_prepare(11);
    let params = FarnebackParams::default();
    let actual = farneback(&g1, &g2, &params);
    let expected = read_flo(&fixture_path_gauss(10, 11));
    let w = actual.width as usize;
    let h = actual.height as usize;
    let mut max_epe = 0.0f32;
    let mut max_pos = (0, 0);
    for y in 0..h {
        for x in 0..w {
            let i = y * w + x;
            let dx = actual.data[i][0] - expected.data[i][0];
            let dy = actual.data[i][1] - expected.data[i][1];
            let epe = dx.hypot(dy);
            if epe > max_epe {
                max_epe = epe;
                max_pos = (x, y);
            }
        }
    }
    let (mx, my) = max_pos;
    let i = my * w + mx;
    eprintln!("Max EPE={max_epe:.4} at ({mx},{my})");
    eprintln!(
        "  actual=[{:.6},{:.6}]",
        actual.data[i][0], actual.data[i][1]
    );
    eprintln!(
        "  expected=[{:.6},{:.6}]",
        expected.data[i][0], expected.data[i][1]
    );
    assert!(mx < w, "max EPE x position in bounds");
    assert!(my < h, "max EPE y position in bounds");
    assert!(max_epe <= 0.5, "pair (10,11): max EPE {max_epe:.4} > 0.5");
    // Check all pixels > 0.5
    let mut count = 0;
    for y in 0..h {
        for x in 0..w {
            let i = y * w + x;
            let dx = actual.data[i][0] - expected.data[i][0];
            let dy = actual.data[i][1] - expected.data[i][1];
            let epe = dx.hypot(dy);
            if epe > 0.4 {
                count += 1;
                if count <= 10 {
                    eprintln!(
                        "  EPE={epe:.4} at ({x},{y}): actual=[{:.4},{:.4}], ref=[{:.4},{:.4}]",
                        actual.data[i][0],
                        actual.data[i][1],
                        expected.data[i][0],
                        expected.data[i][1]
                    );
                }
            }
        }
    }
    eprintln!("Total pixels with EPE > 0.4: {count}");
    assert_eq!(count, 0, "pair (10,11): pixels with EPE > 0.4");
}
